#!/bin/bash -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH


function jruby-install() {
  echo "Installing JRuby..."

  # needed in order to support scaling
  if [ "$OPENSHIFT_JRUBY_VERSION" == "" ]
  then
    export OPENSHIFT_JRUBY_VERSION=`curl http://jruby.org/download | ruby -e "s=ARGF.read;x=/Current Release: JRuby (\d\.\d\.\d)/m.match(s);puts x[1]"`
  fi

  echo "$OPENSHIFT_JRUBY_VERSION" > ${OPENSHIFT_JRUBY_DIR}env/OPENSHIFT_JRUBY_VERSION

  pushd ${OPENSHIFT_RUBY_DIR}/tmp 1>/dev/null

  curl -o jruby.tar.gz http://jruby.org.s3.amazonaws.com/downloads/$OPENSHIFT_JRUBY_VERSION/jruby-bin-$OPENSHIFT_JRUBY_VERSION.tar.gz

  tar xf jruby.tar.gz
  rm -rf jruby.tar.gz
  mkdir -p ${OPENSHIFT_HOMEDIR}/.gem-jruby/bin
  mkdir -p ${OPENSHIFT_RUBY_DIR}/.jruby/

  # jruby executables are stored in ~/.jruby/jruby-${OPENSHIFT_JRUBY_VERSION}/
  mv jruby-${OPENSHIFT_JRUBY_VERSION} ${OPENSHIFT_RUBY_DIR}/.jruby/jruby-${OPENSHIFT_JRUBY_VERSION}

  chmod +x ${OPENSHIFT_RUBY_DIR}/versions/shared/jruby
  ln -s ${OPENSHIFT_RUBY_DIR}/versions/shared/jruby ${OPENSHIFT_RUBY_DIR}/.jruby/jruby

  install-required-gems

  echo "JRuby installed."

  return 0
}

function install-required-gems() {
  ${OPENSHIFT_RUBY_DIR}/.jruby/jruby -S gem install bundler rake
  return 0
}