#!/bin/bash
source "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"


function is_server_installed {
	case $1 in
		"passenger"|"custom")
			;;
		"puma"|"thin"|"unicorn"|"rainbows")
			gem_exists "$1"
			;;
		*)
			echo "WARN: Unknown \"$1\" server" >&2
			exit 1
			;;
	esac
}

function gem_exists() {
	[ "`ruby_context "gem list -i $1"`" == "true" ]
}

# if bundler is used, it's needed to run gems in bundle context
function run_command() {
	if is_bundler_used
	then
		ruby_context "bundle exec $1 "
	else
		ruby_context "$1"
	fi

}

function is_bundler_used() {
	[ -f ${OPENSHIFT_REPO_DIR}/Gemfile ]	
}


function server-control() {
  if [ "$1" = "custom" ]
  then
    ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/server_control $2
  else

    #TODO: add check if server name and action is not empty
    ${OPENSHIFT_RUBY_DIR}/servers/$1/control $2
  fi

}


# check compatibility issues
function no-jruby() {
  if [ "$OPENSHIFT_RUBY_RUNNING_PLATFORM" = "jruby" ]
  then
    echo "This server is does not supported by JRuby."
    exit 1
  fi
}

function only-jruby() {
  if [ "$OPENSHIFT_RUBY_RUNNING_PLATFORM"  != "jruby" ]
  then
    echo "This server is supported only with JRuby"
    exit 1
  fi
}

