#!/bin/bash -e

source "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"

if [ -d ${OPENSHIFT_RUBY_DIR}run/server.state ]
then
    ruby_context 'pumactl --state "${OPENSHIFT_RUBY_DIR}run/server.state" restart'
fi