listen "#{ENV['OPENSHIFT_RUBY_IP']}:#{ENV['OPENSHIFT_RUBY_PORT']}"
pid "#{ENV['OPENSHIFT_SERVER_PID']}"
timeout 30
stdout_path "#{ENV['OPENSHIFT_SERVER_STDOUT_LOG']}"
stderr_path "#{ENV['OPENSHIFT_SERVER_STDERR_LOG']}"

